import { Scope } from "./core";
import { Conditions } from "./conditions";
export declare const makeSelectCommands: (scope: Scope, conditions: Conditions) => {
    seq: (register: string, a: string, b: string) => void;
    seqz: (register: string, a: string) => void;
    sge: (register: string, a: string, b: string) => void;
    sgez: (register: string, a: string) => void;
    sgt: (register: string, a: string, b: string) => void;
    sgtz: (register: string, a: string) => void;
    sle: (register: string, a: string, b: string) => void;
    slez: (register: string, a: string) => void;
    slt: (register: string, a: string, b: string) => void;
    sltz: (register: string, a: string) => void;
    sne: (register: string, a: string, b: string) => void;
    snez: (register: string, a: string) => void;
    sap: (register: string, x: string, y: string, c: string) => void;
    sapz: (register: string, x: string, y: string) => void;
    sna: (register: string, x: string, y: string, c: string) => void;
    snaz: (register: string, x: string, y: string) => void;
    sdse: (register: string, d: string) => void;
    sdns: (register: string, d: string) => void;
    snan: (register: string, v: string) => void;
    snanz: (register: string, v: string) => void;
};
