export declare const patterns: {
    reg: RegExp;
    dev: RegExp;
    recDev: RegExp;
    strStart: RegExp;
    strEnd: RegExp;
    hash: RegExp;
};
export declare const hashStr: (name: string) => number;
export declare const isHash: (value: string) => boolean;
export declare const isNumber: (value: string) => boolean;
export declare const isPort: (value: string) => boolean;
export declare const isRecPort: (value: string) => boolean;
export declare const isSimplePort: (value: string) => boolean;
export declare const isRegister: (value: string) => boolean;
export declare const findDevice: (HashOrName: string | number) => {
    readonly PrefabHash: 1840108251;
    readonly params: {
        readonly PrefabHash: "read";
        readonly CombustionOutput: "read|write";
        readonly CombustionInput: "read|write";
        readonly Combustion: "read|write";
        readonly Activate: "read|write";
        readonly CombustionOutput2: "read|write";
        readonly Maximum: "read|write";
        readonly Error: "read|write";
        readonly Lock: "read|write";
        readonly On: "read|write";
        readonly Mode: "read|write";
        readonly Power: "read|write";
        readonly Open: "read|write";
        readonly Pressure: "read|write";
        readonly PressureOutput: "read|write";
        readonly PressureInput: "read|write";
        readonly PressureOutput2: "read|write";
        readonly RatioCarbonDioxide: "read|write";
        readonly Ratio: "read|write";
        readonly RatioCarbonDioxideInput: "read|write";
        readonly RatioCarbonDioxideOutput2: "read|write";
        readonly RatioNitrogen: "read|write";
        readonly RatioCarbonDioxideOutput: "read|write";
        readonly RatioNitrogenInput: "read|write";
        readonly RatioNitrogenOutput: "read|write";
        readonly RatioNitrogenOutput2: "read|write";
        readonly RatioNitrousOxide: "read|write";
        readonly RatioNitrousOxideInput: "read|write";
        readonly RatioNitrousOxideOutput: "read|write";
        readonly RatioNitrousOxideOutput2: "read|write";
        readonly RatioOxygen: "read|write";
        readonly RatioOxygenInput: "read|write";
        readonly RatioOxygenOutput: "read|write";
        readonly RatioOxygenOutput2: "read|write";
        readonly RatioPollutant: "read|write";
        readonly RatioPollutantOutput: "read|write";
        readonly RatioPollutantInput: "read|write";
        readonly RatioPollutantOutput2: "read|write";
        readonly RatioVolatiles: "read|write";
        readonly RatioVolatilesInput: "read|write";
        readonly RatioVolatilesOutput: "read|write";
        readonly RatioWaterInput: "read|write";
        readonly RatioWater: "read|write";
        readonly RatioVolatilesOutput2: "read|write";
        readonly RatioWaterOutput: "read|write";
        readonly RatioWaterOutput2: "read|write";
        readonly RequiredPower: "read|write";
        readonly Setting: "read|write";
        readonly Temperature: "read|write";
        readonly TemperatureInput: "read|write";
        readonly TemperatureOutput: "read|write";
        readonly TotalMoles: "read|write";
        readonly TemperatureOutput2: "read|write";
        readonly TotalMolesOutput: "read|write";
        readonly TotalMolesInput: "read|write";
        readonly TotalMolesOutput2: "read|write";
    };
    readonly name: "H2Combustor";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 201215010;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly Power: "read|write";
        readonly Charge: "read|write";
    };
    readonly name: "ItemAngleGrinder";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 1385062886;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Power: "read|write";
        readonly Charge: "read|write";
        readonly Activate: "read|write";
    };
    readonly name: "ItemArcWelder";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -869869491;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Charge: "read|write";
        readonly On: "read|write";
        readonly Error: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemBeacon";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 2009673399;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Charge: "read|write";
        readonly Activate: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemDrill";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 374891127;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Quantity: "read|write";
    };
    readonly name: "ItemHardBackpack";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -412551656;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly On: "read|write";
        readonly Temperature: "read|write";
        readonly Pressure: "read|write";
    };
    readonly name: "ItemHardJetpack";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -1758310454;
    readonly params: {
        readonly PrefabHash: "read|write";
        readonly Activate: "read|write";
        readonly Combustion: "read|write";
        readonly Filtration: "read|write";
        readonly Error: "read|write";
        readonly Lock: "read|write";
        readonly On: "read|write";
        readonly PositionY: "read|write";
        readonly PositionX: "read|write";
        readonly PositionZ: "read|write";
        readonly Power: "read|write";
        readonly Pressure: "read|write";
        readonly PressureExternal: "read|write";
        readonly PressureSetting: "read|write";
        readonly RatioCarbonDioxide: "read|write";
        readonly RatioNitrogen: "read|write";
        readonly RatioNitrousOxide: "read|write";
        readonly RatioOxygen: "read|write";
        readonly RatioPollutant: "read|write";
        readonly RatioVolatiles: "read|write";
        readonly RatioWater: "read|write";
        readonly Setting: "read|write";
        readonly SoundAlert: "read|write";
        readonly Temperature: "read|write";
        readonly TemperatureExternal: "read|write";
        readonly TemperatureSetting: "read|write";
        readonly VelocityMagnitude: "read|write";
        readonly VelocityRelativeX: "read|write";
        readonly VelocityRelativeY: "read|write";
    };
    readonly name: "ItemHardSuit";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -84573099;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Combustion: "read|write";
        readonly Flush: "write";
        readonly Lock: "read|write";
        readonly On: "read|write";
        readonly Open: "read|write";
        readonly Power: "read|write";
        readonly PressureSetting: "read|write";
        readonly Pressure: "read|write";
        readonly RatioCarbonDioxide: "read|write";
        readonly RatioNitrogen: "read|write";
        readonly RatioNitrousOxide: "read|write";
        readonly RatioPollutant: "read|write";
        readonly RatioOxygen: "read|write";
        readonly RatioVolatiles: "read|write";
        readonly RatioWater: "read|write";
        readonly Vertical: "read|write";
        readonly Temperature: "read|write";
    };
    readonly name: "ItemHardsuitHelmet";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 1969189000;
    readonly params: {
        readonly PrefabHash: "read";
        readonly On: "read|write";
        readonly Activate: "read|write";
        readonly Pressure: "read|write";
        readonly Temperature: "read|write";
    };
    readonly name: "ItemJetpackBasic";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -743968726;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Charge: "read|write";
        readonly Error: "read|write";
        readonly On: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemLabeller";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 240174650;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly Charge: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemMKIIAngleGrinder";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -2061979347;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly Charge: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemMKIIArcWelder";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 324791548;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly Charge: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemMKIIDrill";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -1875271296;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly Mode: "read|write";
        readonly Charge: "read|write";
        readonly Error: "read|write";
        readonly On: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemMKIIMiningDrill";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 1470787934;
    readonly params: {
        readonly PrefabHash: "read";
    };
    readonly name: "ItemMiningBeltMKII";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 1055173191;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Charge: "read|write";
        readonly Activate: "read|write";
        readonly Error: "read|write";
        readonly On: "read|write";
        readonly Mode: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemMiningDrill";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -1663349918;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly Charge: "read|write";
        readonly Mode: "read|write";
        readonly Error: "read|write";
        readonly On: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemMiningDrillHeavy";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 1467558064;
    readonly params: {
        readonly PrefabHash: "read";
    };
    readonly name: "ItemMkIIToolbelt";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 982514123;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Charge: "read|write";
        readonly On: "read|write";
        readonly Lock: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemNVG";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 173023800;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly Mode: "read|write";
        readonly Charge: "read|write";
        readonly On: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemPlantSampler";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 678483886;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Charge: "read|write";
        readonly Error: "read|write";
        readonly On: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemRemoteDetonator";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -1176140051;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Charge: "read|write";
        readonly On: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemSensorLenses";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 714830451;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Combustion: "read|write";
        readonly Flush: "write";
        readonly Lock: "read|write";
        readonly On: "read|write";
        readonly Open: "read|write";
        readonly Power: "read|write";
        readonly Pressure: "read|write";
        readonly PressureSetting: "read|write";
        readonly RatioCarbonDioxide: "read|write";
        readonly RatioNitrousOxide: "read|write";
        readonly RatioOxygen: "read|write";
        readonly RatioNitrogen: "read|write";
        readonly RatioPollutant: "read|write";
        readonly RatioVolatiles: "read|write";
        readonly RatioWater: "read|write";
        readonly Temperature: "read|write";
        readonly Vertical: "read|write";
    };
    readonly name: "ItemSpaceHelmet";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -1260618380;
    readonly params: {
        readonly PrefabHash: "read";
        readonly On: "read|write";
        readonly Activate: "read|write";
        readonly Pressure: "read|write";
        readonly Temperature: "read|write";
    };
    readonly name: "ItemSpacepack";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 111280987;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly Charge: "read|write";
        readonly Error: "read|write";
        readonly Mode: "read|write";
        readonly On: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemTerrainManipulator";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -598730959;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Quantity: "read|write";
        readonly Charge: "read|write";
        readonly On: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "ItemWearLamp";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -463037670;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly Error: "read|write";
        readonly ClearMemory: "write";
        readonly CompletionRatio: "read|write";
        readonly ImportCount: "read|write";
        readonly ExportCount: "read|write";
        readonly Lock: "read|write";
        readonly On: "read|write";
        readonly Open: "read|write";
        readonly Power: "read|write";
        readonly Reagents: "read|write";
        readonly RequiredPower: "read|write";
        readonly RecipeHash: "read|write";
    };
    readonly name: "StructureAdvancedPackagingMachine";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 336213101;
    readonly params: {
        readonly PrefabHash: "read";
        readonly ClearMemory: "write";
        readonly Activate: "read|write";
        readonly CompletionRatio: "read|write";
        readonly Error: "read|write";
        readonly ImportCount: "read|write";
        readonly On: "read|write";
        readonly Lock: "read|write";
        readonly ExportCount: "read|write";
        readonly Power: "read|write";
        readonly Open: "read|write";
        readonly Reagents: "read|write";
        readonly RequiredPower: "read|write";
        readonly RecipeHash: "read|write";
    };
    readonly name: "StructureAutolathe";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -1672404896;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly ClearMemory: "write";
        readonly CompletionRatio: "read|write";
        readonly Error: "read|write";
        readonly ExportCount: "read|write";
        readonly ImportCount: "read|write";
        readonly Lock: "read|write";
        readonly On: "read|write";
        readonly Reagents: "read|write";
        readonly Open: "read|write";
        readonly Power: "read|write";
        readonly RecipeHash: "read|write";
        readonly RequiredPower: "read|write";
    };
    readonly name: "StructureAutomatedOven";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -1149857558;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Lock: "read|write";
        readonly Error: "read|write";
        readonly Maximum: "read|write";
        readonly Power: "read|write";
        readonly On: "read|write";
        readonly Ratio: "read|write";
        readonly RequiredPower: "read|write";
        readonly Setting: "read|write";
    };
    readonly name: "StructureBackPressureRegulator";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -1613497288;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Lock: "read|write";
        readonly Power: "read|write";
        readonly On: "read|write";
        readonly RequiredPower: "read|write";
        readonly Setting: "read|write";
    };
    readonly name: "StructureBasketHoop";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 690945935;
    readonly params: {
        readonly PrefabHash: "read";
        readonly ClearMemory: "write";
        readonly Error: "read|write";
        readonly ExportCount: "read|write";
        readonly ImportCount: "read|write";
        readonly On: "read|write";
        readonly Open: "read|write";
        readonly Reagents: "read|write";
        readonly Power: "read|write";
        readonly RequiredPower: "read|write";
    };
    readonly name: "StructureCentrifuge";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -128473777;
    readonly params: {
        readonly PrefabHash: "read";
        readonly On: "read|write";
        readonly Power: "read|write";
        readonly Error: "read|write";
        readonly RequiredPower: "read|write";
        readonly Setting: "read|write";
    };
    readonly name: "StructureCircuitHousing";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 1238905683;
    readonly params: {
        readonly PrefabHash: "read";
        readonly CombustionInput: "read|write";
        readonly ClearMemory: "write";
        readonly Combustion: "read|write";
        readonly CombustionLimiter: "read|write";
        readonly CombustionOutput: "read|write";
        readonly Error: "read|write";
        readonly ExportCount: "read|write";
        readonly ImportCount: "read|write";
        readonly Lock: "read|write";
        readonly On: "read|write";
        readonly Power: "read|write";
        readonly Pressure: "read|write";
        readonly PressureInput: "read|write";
        readonly Open: "read|write";
        readonly PressureOutput: "read|write";
        readonly RatioCarbonDioxide: "read|write";
        readonly RatioNitrogen: "read|write";
        readonly RatioCarbonDioxideInput: "read|write";
        readonly RatioCarbonDioxideOutput: "read|write";
        readonly RatioNitrogenInput: "read|write";
        readonly RatioNitrogenOutput: "read|write";
        readonly RatioNitrousOxide: "read|write";
        readonly RatioOxygen: "read|write";
        readonly RatioNitrousOxideOutput: "read|write";
        readonly RatioNitrousOxideInput: "read|write";
        readonly RatioOxygenOutput: "read|write";
        readonly RatioPollutant: "read|write";
        readonly RatioOxygenInput: "read|write";
        readonly RatioPollutantInput: "read|write";
        readonly RatioPollutantOutput: "read|write";
        readonly RatioVolatiles: "read|write";
        readonly RatioVolatilesInput: "read|write";
        readonly RatioVolatilesOutput: "read|write";
        readonly RatioWater: "read|write";
        readonly RatioWaterInput: "read|write";
        readonly RequiredPower: "read|write";
        readonly RatioWaterOutput: "read|write";
        readonly Rpm: "read|write";
        readonly Stress: "read|write";
        readonly Temperature: "read|write";
        readonly TemperatureInput: "read|write";
        readonly TemperatureOutput: "read|write";
        readonly Throttle: "read|write";
        readonly TotalMoles: "read|write";
        readonly TotalMolesInput: "read|write";
        readonly TotalMolesOutput: "read|write";
    };
    readonly name: "StructureCombustionCentrifuge";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -626563514;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Error: "read|write";
        readonly LineNumber: "read|write";
        readonly Lock: "read|write";
        readonly On: "read|write";
        readonly Open: "read|write";
        readonly Power: "read|write";
        readonly PowerRequired: "read|write";
    };
    readonly name: "StructureComputer";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 265720906;
    readonly params: {
        readonly PrefabHash: "read";
        readonly ClearMemory: "write";
        readonly ExportCount: "read|write";
        readonly Error: "read|write";
        readonly ImportCount: "read|write";
        readonly On: "read|write";
        readonly Maximum: "read|write";
        readonly Power: "read|write";
        readonly Ratio: "read|write";
        readonly RequiredPower: "read|write";
        readonly Setting: "read|write";
    };
    readonly name: "StructureDeepMiner";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 1307165496;
    readonly params: {
        readonly PrefabHash: "read";
        readonly ClearMemory: "write";
        readonly Activate: "read|write";
        readonly ImportCount: "read|write";
        readonly CompletionRatio: "read|write";
        readonly Error: "read|write";
        readonly ExportCount: "read|write";
        readonly Lock: "read|write";
        readonly On: "read|write";
        readonly Power: "read|write";
        readonly Open: "read|write";
        readonly Reagents: "read|write";
        readonly RecipeHash: "read|write";
        readonly RequiredPower: "read|write";
    };
    readonly name: "StructureElectronicsPrinter";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -1888248335;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly ClearMemory: "write";
        readonly Error: "read|write";
        readonly CompletionRatio: "read|write";
        readonly ImportCount: "read|write";
        readonly ExportCount: "read|write";
        readonly Lock: "read|write";
        readonly On: "read|write";
        readonly Reagents: "read|write";
        readonly Open: "read|write";
        readonly Power: "read|write";
        readonly RequiredPower: "read|write";
        readonly RecipeHash: "read|write";
    };
    readonly name: "StructureHydraulicPipeBender";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 1005491513;
    readonly params: {
        readonly PrefabHash: "read";
        readonly On: "read|write";
    };
    readonly name: "StructureIgniter";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -851746783;
    readonly params: {
        readonly PrefabHash: "read";
        readonly LineNumber: "read|write";
        readonly Setting: "read|write";
    };
    readonly name: "StructureLogicMemory";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 209854039;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Error: "read|write";
        readonly Maximum: "read|write";
        readonly Lock: "read|write";
        readonly Power: "read|write";
        readonly Ratio: "read|write";
        readonly On: "read|write";
        readonly RequiredPower: "read|write";
        readonly Setting: "read|write";
    };
    readonly name: "StructurePressureRegulator";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 906210602;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Quantity: "read|write";
        readonly Activate: "read|write";
        readonly ClearMemory: "write";
        readonly Error: "read|write";
        readonly ExportCount: "read|write";
        readonly ImportCount: "read|write";
        readonly Maximum: "read|write";
        readonly Lock: "read|write";
        readonly Mode: "read|write";
        readonly On: "read|write";
        readonly Open: "read|write";
        readonly Power: "read|write";
        readonly Ratio: "read|write";
        readonly RequiredPower: "read|write";
        readonly Setting: "read|write";
    };
    readonly name: "StructureRocketModuleSilo";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -641491515;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly ClearMemory: "write";
        readonly CompletionRatio: "read|write";
        readonly Error: "read|write";
        readonly ExportCount: "read|write";
        readonly ImportCount: "read|write";
        readonly Lock: "read|write";
        readonly On: "read|write";
        readonly Reagents: "read|write";
        readonly Power: "read|write";
        readonly RecipeHash: "read|write";
        readonly Open: "read|write";
        readonly RequiredPower: "read|write";
    };
    readonly name: "StructureSecurityPrinter";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -2138748650;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Activate: "read|write";
        readonly InterrogationProgress: "read|write";
        readonly Horizontal: "read|write";
        readonly Error: "read|write";
        readonly MinimumWattsToContact: "read|write";
        readonly On: "read|write";
        readonly RequiredPower: "read|write";
        readonly Setting: "read|write";
        readonly Power: "read|write";
        readonly SignalStrength: "read|write";
        readonly SignalID: "read|write";
        readonly SizeZ: "read|write";
        readonly SizeX: "read|write";
        readonly TargetPadIndex: "read|write";
        readonly VelocityRelativeZ: "read|write";
        readonly Volume: "read|write";
    };
    readonly name: "StructureSmallSatelliteDish";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -465741100;
    readonly params: {
        readonly PrefabHash: "read";
        readonly CompletionRatio: "read|write";
        readonly Activate: "read|write";
        readonly ClearMemory: "write";
        readonly Error: "read|write";
        readonly ExportCount: "read|write";
        readonly ImportCount: "read|write";
        readonly On: "read|write";
        readonly Lock: "read|write";
        readonly Open: "read|write";
        readonly Power: "read|write";
        readonly Reagents: "read|write";
        readonly RecipeHash: "read|write";
        readonly RequiredPower: "read|write";
    };
    readonly name: "StructureToolManufactory";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: -385323479;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Charge: "read|write";
        readonly Mode: "read|write";
        readonly Error: "read|write";
        readonly On: "read|write";
        readonly Lock: "read|write";
        readonly Open: "read|write";
        readonly Power: "read|write";
    };
    readonly name: "WeaponPistolEnergy";
    readonly description: "";
    readonly slot_count: 0;
} | {
    readonly PrefabHash: 1154745374;
    readonly params: {
        readonly PrefabHash: "read";
        readonly Mode: "read|write";
        readonly Error: "read|write";
        readonly Charge: "read|write";
        readonly Lock: "read|write";
        readonly On: "read|write";
        readonly Power: "read|write";
        readonly Open: "read|write";
    };
    readonly name: "WeaponRifleEnergy";
    readonly description: "";
    readonly slot_count: 0;
};
